"""Add AnalysisCache table

Revision ID: 197c8f562369
Revises: 0c194549429b
Create Date: 2026-01-22 08:39:57.565120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197c8f562369'
down_revision = '0c194549429b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_cache_input_hash'), ['input_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_cache_input_hash'))

    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
