"""add action item approval fields

Revision ID: b4a0c3a52e5a
Revises: 32a43eb01077
Create Date: 2026-01-29 00:11:55.019005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a0c3a52e5a'
down_revision = '32a43eb01077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
