"""Initial migration

Revision ID: c039ca308387
Revises: 
Create Date: 2025-12-23 13:07:12.619310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c039ca308387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('facilitator_name', sa.String(length=255), nullable=True),
    sa.Column('num_responses', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('person_in_charge', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('common_issues',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('common_issue', sa.Text(), nullable=False),
    sa.Column('evidence_signal', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('question_label', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_ratings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('facilitator_understanding', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('learning_mechanics', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('qa_support', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('problem_articulation', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('session_pace', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('tools_helpfulness', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('repeatability', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('learning_objectives', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('overall_quality', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_ratings')
    op.drop_table('question_analyses')
    op.drop_table('common_issues')
    op.drop_table('action_items')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
